### ISSUE TITLE
Upon examination of leaking your 7 year old photo…

### ISSUE THREAD

**Issue by TheHackerFalcon** [MrWaltz-b14/OogaBooga-space-consumer.#1]
Your hairline is ugly asf

**Comment by MrWaltz-b14** [comment]
you look goofy as well dont even.

**Comment by MrWaltz-b14** [comment]
first you lie to yourself also you cant pull anything. plus yes.

**Comment by TheHackerFalcon** [comment]
First of all, there is no possible way to yourself. The human psyche finds it virtually impossible to converse in itself a false truth, because whenever it says that truth it will always remember its falsification. Your second statement is simply false. As for your last statement, where do we start?

**Comment by MrWaltz-b14** [comment]
invited you to the project, second at least 70thousand pl rated me 10/10

**Comment by MrWaltz-b14** [comment]
discord?

**Comment by TheHackerFalcon** [comment]
70,000 people? The entire city of Fort Wayne is populated by give or take 250,000 people, so you somehow got around 1/3 to 1/4 of them to give you a average rating of 10/10?

**Comment by TheHackerFalcon** [comment]
Nah, I can’t do Discord.

**Comment by MrWaltz-b14** [comment]
why not

**Comment by MrWaltz-b14** [comment]
also, JOIN THE PROJECT

**Comment by TheHackerFalcon** [comment]
Wait, lemme switch accounts first.

**Comment by MrWaltz-b14** [comment]
we could make the website in django? its actually good for that tbh

**Comment by El-Qassam** [comment]
Nah, I don’t have the patience for Django.

**Comment by MrWaltz-b14** [comment]
wdym?

**Comment by MrWaltz-b14** [comment]
what else would we make it in?

**Comment by El-Qassam** [comment]
Had to go for a sec. I can’t be on Discord very much because:
1. My PC is recovering after the rough ride it took with the partitions.
2. Curbing online time.
3. I hid it on my phone home page so I don’t tempt myself.
4. I don’t really wanna overdose on Ethan and Sam’s low IQ levels.

**Comment by MrWaltz-b14** [comment]
thats stupid, using github issue messages is kinda sucky, whats wrong with django?

**Comment by El-Qassam** [comment]
I don’t have the frame of mind to re-do the trauma of working on Django, it requires a ridiculous amount of patience that I don’t have to keep fixing broken launches. At least that was _my_ experience from about a year ago.

**Comment by MrWaltz-b14** [comment]
well what else would we use? flask?

**Comment by El-Qassam** [comment]
Hey, genius idea incoming: How about we actually use the group forums that actually took me time to build? 🤯

**Comment by MrWaltz-b14** [comment]
oh yeah sure

**Comment by MrWaltz-b14** [comment]
okay im on the websittee
e

**Comment by El-Qassam** [comment]
Did you sign in?

**Comment by MrWaltz-b14** [comment]
yeah...

**Comment by El-Qassam** [comment]
Ok

**Comment by MrWaltz-b14** [comment]
i just made a post

**Comment by El-Qassam** [comment]
I’m on

**Comment by El-Qassam** [comment]
Hi
